language: bash
sudo: required
services:
  - docker
env:
  global:
  - DOCKER_REPO=keltonkarboviak
  - DOCKER_USERNAME=keltonkarboviak
  - secure: AnAUYRtcCTV9+C6X1oWtY2yHQ1mAlJGR+kzSflBjiuuNtupwNJ4P9U312E2SzTdwOial0j2YreNoMNLJlu5prelHnVPQzUTpliiYpk4uFIkyBIjBU0gs58rgwkat2YZpH82uuVDbeDXnvLf/K9t7tuyfWBz3t+cUSyyR0fysr6PlxB2SuEx3IuIl9bpUOPINpaiyFEGpOTREhLAhFgv2IRkC3paoqiEJtpGZ13hczzaowHmymPDHwyZzk6HaConiDUZYQKNWy2n+TQnoyjmhuRWkrSOFePwR22T62B2IYPyJDa8LCkV4SuflBg6Fov4pBX6Y/42lymF1hJu1OFA3cGEsWk+6SVb4mxKpt0C2R3lOjE5sLVu3ZXE3WKpll2//459Mo3ZRFQWVxFwVRIayxLk78udIZFlIM6U+tWY9jr+9av5cB3eIOhxN8ntqek6nAXWABEBvCBnotd7DnIz3gohA4uHrrH1gW+kX96s44Otzvlohh/aHggX7gAYOAFT1CktLcbdiNOsABsANcQl1dP21MHZaeAvLrXQobDZVV1+9jB8+4B6he1bSBzJuRWvkr+HzUXnhCygAJ9iLkCfofQhI9mLvTbr+rkyU2t5/NnvDB6/61b7V3qBgxAmaKLn9ARug5pvG0R6N+mlxIGG8d0zTmm7QK96otaOoWci5wyc=
  matrix:
  - LANGUAGE=python VERSION=2.7
  - LANGUAGE=python VERSION=3.6
  - LANGUAGE=ruby VERSION=2.4

before_script:
  - env | sort
  - cd "${LANGUAGE}-builder/"
  - LANGUAGE_UPPER=$(echo $LANGUAGE | tr [:lower:] [:upper:])
  - IMAGE="${LANGUAGE}-builder"
  - IMAGE="$REPO/${LANGUAGE}-builder:$VERSION"

script:
  - echo "** Building $IMAGE in $PWD **"
  - docker build --build-arg ${LANGUAGE_UPPER}_VERSION=$VERSION -t "$REPO/$IMAGE:$VERSION" .

after_script:
  - docker images

deploy:
  provider: script
  script: bash docker_push $REPO $IMAGE $VERSION
  on:
    branch: master

notifications:
  slack:
    secure: avDC28JnaZPyTTUkaZpWSZnbjo0CspuU4ATnm8aBkIx6IljZHn4GTcqERfFJNCbUNlbAjMydIXz+lTouurx8s1m0EWDIaxeizxxEDlb7U9iLo2ZdgpJ9ZL3LO8G91OCoRWx7Vp7uGfZF8RpkOkYuQiU/4svsgF5940QOEPlEXkcLyCtpMeEFL+47APWv6nW7ENAArogoxWSjYJIY/EqWPiCOnHHYdigDgfTN8ZEIeu/m99PPreHhUb1+BlY2CpmPmB9tPXp+2vGCuEkTfSlyKIubQd/xS4ebcEmt1EQoDpTVQAz16O37q/hafhvFEDfG8y79dZni1x2zhPtFJ1dCUZUru0LtqAARu5LNs1Fm0w8bptWqkq1kdIHiOwTwzWFLfiTCJytwEa3m6bIAREFqwkDCZwutXHQJneAfEoSS9cVikxW9TacpLJ7qJdyfFCt390YGi3JVmGt0vqed+EjrL954BjQAN/6I7/n7RFZRzVpLbBxbCxbq87zzuJbp5sGmXlL7tJH+wmq/fVm+/BiQgUZhkjnAh+FwSb2DEarvSzbWBlIVZuPmxzUQ1RbF6VL9/vdzXVNDyDKHPFtllRtR3xsGuB1KIXXrLkY/2JjXC5fE0LziGtlqcT71t1fZSfrBJBbqTZcS+DlOd/ZuV1LJwS9ygK1UaOdI89DaI/gBpao=
